#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#export the XDG user variables
if [ -x "$(command -v ld-export-xdg-user-vars)" ]; then
  ld-export-xdg-user-vars
fi

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"


#disable screen blanking
xset s off

#set background
if [ -x "$(command -v ld-set-background)" ]; then
  ld-set-background
fi
